name: snt_manager
description: SNT Manager - Sultan Network Management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.11.5'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  webview_flutter: ^4.7.0
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#0F0F1A"
  adaptive_icon_foreground: "assets/images/app_icon.png"