name: snt_manager
description: Sultan Net Manager App
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  local_auth: ^2.2.0

flutter:
  uses-material-design: true
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf